In [1]:
from keras.models import load_model
import cv2
import numpy as np
model_path = 'D:/star/GoogleNetV4_class_ORI_20191015/model_20200224_epoch250/googlenetV4_classification_ORI_20200224_epoch250_shuffle.h5'

model = load_model(model_path)

img=cv2.imread('D:\\star\\GoogleNetV4_class_ORI_20191015\\test\\2_Speciesmix (69)_2.jpg')

img=cv2.resize(img,(299,299))
img=img.reshape(-1, 299, 299, 3)
predict_test = model.predict(img)
predict = np.argmax(predict_test,axis=1)
print(predict)
# if predict == 1:
#     print("公")
# elif predict == 0:
#     print("母")

#print(predict_test)

Using TensorFlow backend.


[1]


In [2]:
#將speciesmix標記轉成對應字串名稱
def decoding(label):
    n_label = label
    if (label.isdigit()):
        if (label=="7"):
            n_label="Aedesaeg"
        elif (label=="0"):
            n_label="Albopictus"
        elif (label=="1"):
            n_label="Armigeres"
        elif (label=="4"):
            n_label="Culextrit"
        elif (label=="6"):
            n_label="Chironom"       
        elif (label=="5"):
            n_label="Culexpip"
        elif (label=="2"):
            n_label="Culpip" 
        elif (label=="3"):
            n_label="Anopheles" 
            
    return n_label

In [3]:
import os
import pandas as pd
import shutil

test_data='D:\\star\\GoogleNetV4_class_ORI_20191015\\test\\'
classes=["Anopheles","Culpip","Culexpip","Chironom","Culextrit","Armigeres","Albopictus","Aedesaeg"] #預測標記
confusion_matrix = np.zeros((8,8)) #混淆矩陣8*8大小
for root,dirs,files in os.walk(test_data): #讀取資料夾影像
    for f in files:
        img=cv2.imread(os.path.join(root,f))
        #print(os.path.join(root,f))
        img=cv2.resize(img,(299,299))
        img=img.reshape(-1, 299, 299, 3)
        predict_test = model.predict(img)
        predict = np.argmax(predict_test,axis=1)
        
        #if (f.split("_")[0])
#         print(f.split("_")[0].isdigit()) #true-false              
        #print(f.split("_")[0].split(' ')[0])
    
        label=decoding(f.split("_")[0].split(' ')[0])
        
        
        confusion_matrix[classes.index(label)][predict[0]] += 1
        if (label!=classes[predict[0]]):
#             shutil.copy(os.path.join(root,f), 'D:\\star\\GoogleNetV4_sex_GYS0to255\\model\\testing_errorIMG')
            if not (os.path.isdir('D:\\star\\GoogleNetV4_class_ORI_20191015\\testing_20200224_epoch250\\testing_err\\{}_{}'.format(label, classes[predict[0]]))):
                  os.mkdir('D:\\star\\GoogleNetV4_class_ORI_20191015\\testing_20200224_epoch250\\testing_err\\{}_{}'.format(label, classes[predict[0]]))
            shutil.copy(os.path.join(root,f), 'D:\\star\\GoogleNetV4_class_ORI_20191015\\testing_20200224_epoch250\\testing_err\\{}_{}'.format(label, classes[predict[0]]))

df = pd.DataFrame(confusion_matrix)
df.columns = ["Anopheles","Culpip","Culexpip","Chironom","Culextrit","Armigeres","Albopictus","Aedesaeg"]
df.index = ["Anopheles","Culpip","Culexpip","Chironom","Culextrit","Armigeres","Albopictus","Aedesaeg"]
print(df)
df.to_csv('D:\\star\\GoogleNetV4_class_ORI_20191015\\testing_20200224_epoch250\\result2.csv')            
        

            Anopheles  Culpip  Culexpip  Chironom  Culextrit  Armigeres  \
Anopheles       289.0     3.0       0.0       0.0        2.0        0.0   
Culpip            1.0   263.0       0.0       0.0        2.0        0.0   
Culexpip          0.0     0.0     255.0       1.0        0.0        0.0   
Chironom          0.0     0.0       0.0     266.0        0.0        0.0   
Culextrit         1.0     6.0       1.0       1.0      479.0        5.0   
Armigeres         0.0     0.0       2.0       0.0        4.0      307.0   
Albopictus        0.0     0.0       0.0       0.0        0.0        0.0   
Aedesaeg          1.0     0.0       0.0       0.0        2.0        7.0   

            Albopictus  Aedesaeg  
Anopheles          0.0       1.0  
Culpip             0.0       1.0  
Culexpip           0.0       0.0  
Chironom           0.0       0.0  
Culextrit          0.0       9.0  
Armigeres          0.0       8.0  
Albopictus       234.0       2.0  
Aedesaeg           0.0     368.0  


In [4]:
for i in range(8):
    confusion_matrix[i]=confusion_matrix[i]/np.sum(confusion_matrix[i])
print(np.round(confusion_matrix,2))

df = pd.DataFrame(np.round(confusion_matrix,4))
df.columns = ["Anopheles","Culpip","Culexpip","Chironom","Culextrit","Armigeres","Albopictus","Aedesaeg"]
df.index = ["Anopheles","Culpip","Culexpip","Chironom","Culextrit","Armigeres","Albopictus","Aedesaeg"]
print(df)
df.to_csv('D:\\star\\GoogleNetV4_class_ORI_20191015\\testing_20200224_epoch250\\result.csv')

[[0.98 0.01 0.   0.   0.01 0.   0.   0.  ]
 [0.   0.99 0.   0.   0.01 0.   0.   0.  ]
 [0.   0.   1.   0.   0.   0.   0.   0.  ]
 [0.   0.   0.   1.   0.   0.   0.   0.  ]
 [0.   0.01 0.   0.   0.95 0.01 0.   0.02]
 [0.   0.   0.01 0.   0.01 0.96 0.   0.02]
 [0.   0.   0.   0.   0.   0.   0.99 0.01]
 [0.   0.   0.   0.   0.01 0.02 0.   0.97]]
            Anopheles  Culpip  Culexpip  Chironom  Culextrit  Armigeres  \
Anopheles      0.9797  0.0102    0.0000    0.0000     0.0068     0.0000   
Culpip         0.0037  0.9850    0.0000    0.0000     0.0075     0.0000   
Culexpip       0.0000  0.0000    0.9961    0.0039     0.0000     0.0000   
Chironom       0.0000  0.0000    0.0000    1.0000     0.0000     0.0000   
Culextrit      0.0020  0.0120    0.0020    0.0020     0.9542     0.0100   
Armigeres      0.0000  0.0000    0.0062    0.0000     0.0125     0.9564   
Albopictus     0.0000  0.0000    0.0000    0.0000     0.0000     0.0000   
Aedesaeg       0.0026  0.0000    0.0000    0.0000     0

In [ ]:
kfold =KFold(n_splits=5, shuffle=True, random_state=7)
tr_cvscores = []
test_cvscores = []
for ktrain, ktest in kfold.split(tr_img_data, tr_lbl_data):
    #history = model.fit(x=tr_img_data[ktrain], y=tr_lbl_data[ktrain], batch_size=16, epochs=100,verbose=2,validation_split=0.2)
    #model.save(str(times)+'_mosq-res34.h5')
    #times=times+1
    tr_score, tr_acc = model.evaluate(tr_img_data[ktrain],tr_lbl_data[ktrain])
    print('Training score:', tr_score)
    print('Training accuracy:', tr_acc)
    tr_cvscores.append(tr_acc * 100)
    test_score, test_acc = model.evaluate(tr_img_data[ktest],tr_lbl_data[ktest])
    print('Test score:', test_score)
    print('Test accuracy:', test_acc)
    test_cvscores.append(test_acc * 100)
print(tr_cvscores)
print(test_cvscores)